"""
Webhook event types for Saleor App SDK
"""

from enum import Enum


class WebhookEventType(str, Enum):
    ORDER_CREATED = "ORDER_CREATED"
    ORDER_UPDATED = "ORDER_UPDATED"
    ORDER_PAID = "ORDER_PAID"
    ORDER_FULLY_PAID = "ORDER_FULLY_PAID"
    ORDER_REFUNDED = "ORDER_REFUNDED"
    ORDER_CANCELLED = "ORDER_CANCELLED"
    ORDER_FULFILLED = "ORDER_FULFILLED"
    PRODUCT_CREATED = "PRODUCT_CREATED"
    PRODUCT_UPDATED = "PRODUCT_UPDATED"
    PRODUCT_DELETED = "PRODUCT_DELETED"
    CUSTOMER_CREATED = "CUSTOMER_CREATED"
    CUSTOMER_UPDATED = "CUSTOMER_UPDATED"
    CHECKOUT_CREATED = "CHECKOUT_CREATED"
    CHECKOUT_UPDATED = "CHECKOUT_UPDATED"
    # Add more as needed
