"""
Permission enums for Saleor App SDK
"""

from enum import Enum


class SaleorPermission(str, Enum):
    MANAGE_ORDERS = "MANAGE_ORDERS"
    MANAGE_PRODUCTS = "MANAGE_PRODUCTS"
    MANAGE_USERS = "MANAGE_USERS"
    MANAGE_STAFF = "MANAGE_STAFF"
    MANAGE_CHANNELS = "MANAGE_CHANNELS"
    MANAGE_DISCOUNTS = "MANAGE_DISCOUNTS"
    MANAGE_PLUGINS = "MANAGE_PLUGINS"
    MANAGE_SETTINGS = "MANAGE_SETTINGS"
    MANAGE_PAGES = "MANAGE_PAGES"
    MANAGE_MENUS = "MANAGE_MENUS"
    MANAGE_TRANSLATIONS = "MANAGE_TRANSLATIONS"
    MANAGE_CHECKOUTS = "MANAGE_CHECKOUTS"
    HANDLE_PAYMENTS = "HANDLE_PAYMENTS"
    MANAGE_GIFT_CARD = "MANAGE_GIFT_CARD"
